# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      # copy exactly the joints from gripper_controller in ros2_controllers.yaml, e.g.
      - right_gripper_l_finger_joint